/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RtThread_RtThread */

#ifndef _Included_RtThread_RtThread
#define _Included_RtThread_RtThread
#ifdef __cplusplus
extern "C" {
#endif

int setAffinity(int core_id);
long getPthredSelf();

/*
 * Class:     RtThread_RtThread
 * Method:    getPthreadSelf
 * Signature: ()I
 */
JNIEXPORT jlong JNICALL Java_RtThread_RtJNI_getPthreadSelf(JNIEnv *, jclass);


/*
 * Class:     RtThread_RtThread
 * Method:    getPid
 * Signature: ()I
 */

JNIEXPORT jlong JNICALL Java_RtThread_RtJNI_getPid(JNIEnv *,jobject);

/*
 * Class:     RtThread_RtThread
 * Method:    setPriorit
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_RtThread_RtJNI_setPriorit(JNIEnv *, jclass, jint,
		jint);

/*
 * Class:     RtThread_RtThread
 * Method:    getPriorit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_RtThread_RtJNI_getPriorit(JNIEnv *, jclass);
/*
 * Class:     RtThread_RtThread
 * Method:    getPriorit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_RtThread_RtJNI_getPrioritThread(JNIEnv *, jclass,
		jlong);
/*
 * Class:     RtThread_RtThread
 * Method:    setAffinity
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_RtThread_RtJNI_setAffinity(JNIEnv *, jclass, jint);

/*
 * Class:     RtThread_RtThread
 * Method:    setPrioritThread
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_RtThread_RtJNI_setPrioritThread(JNIEnv *, jclass,
		jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
